### create user
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "posol2008@gmail.com",
  "password": "123"
}

### search user by status
GET http://localhost:8080/api/internal/users/search?status=active
Accept: application/json

### get private user
GET http://localhost:8080/api/users/25
Accept: application/json

### get public user
GET http://localhost:8080/api/users/25
Accept: application/json
X-Public: true

### create user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "first_name": "Aleksandr",
  "last_name": "Poslovskii",
  "email": "posol2008@gmail.com",
  "password": "123"
}

### update delta user
PATCH http://localhost:8080/api/users/20
Content-Type: application/json

{
  "email": "posol2008@gmail.com2"
}

### update full user
PUT http://localhost:8080/api/users/24
Content-Type: application/json

{
  "id": 5,
  "first_name": "Aleksandr",
  "last_name": "Poslovskii",
  "email": "posol2008@gmail.com",
  "date_created": "Tue May 19 08:07:57 +0000 UTC 2020"
}

### delete user
DELETE http://localhost:8080/api/users/22
Content-Type: application/json
